keys:
  - &gtrun 6A43333DBD6C7C70B7A1DB59761C8EBEA940960E
  - &guangtao age1j7vceksgttjv26lkn8f5xr2zlyxtp57ulmccgys8eurhsv5cn32qclkwan
creation_rules:
  - path_regex: (secrets|secrets/keys/rootIdentityFile)/[^/]+\.(yaml|keytab)$
    key_groups:
      - pgp:
        - *gtrun
