[nomad-qemu-cluster.info]
ipv4 = "10.0.2.15"

[nomad-qemu-cluster.services.nomad]
consul.address = "10.0.2.15:8500"

[nomad-qemu-cluster.services.consul]
retry_join = ["10.0.2.15"]
client_addr = "10.0.2.15"
ports.grpc = 8502
interface.bind = "enp0s6"
interface.advertise = "enp0s6"

[nomad-tenzir-vast.info]
ipv4 = "127.0.0.1"

[nomad-tenzir-vast.services.vast]
endpoint = "127.0.0.1:42000"

[nomad-tenzir-opencti.info]
ipv4 = "127.0.0.1"

[nomad-tenzir-opencti.services.vast]
endpoint = "127.0.0.1:42000"

[nomad-airflow.info]
ipv4 = "127.0.0.1"
