[tap-qemu-host.info]
ip = "10.0.0.1"

[tap-qemu-host.services.vast]
endpoint = "10.0.0.1:42000"

##############
# qemu hosts #
##############
[tap-qemu-1.info]
ipv4 = "10.0.0.12"

[tap-qemu-1.services.vast]
endpoint = "10.0.0.1:42000"

[tap-qemu-1.services.vast-client]
endpoint = "10.0.0.1:42000"
broker = false
pcap.enable = true
pcap.interface = "enp0s5"

[tap-qemu-2.info]
ipv4 = "10.0.0.47"

[tap-qemu-2.services.vast]
endpoint = "10.0.0.1:42000"

[tap-qemu-2.services.vast-client]
endpoint = "10.0.0.1:42000"
broker = false
pcap.enable = true
pcap.interface = "enp0s5"




####################
# tap-firecrackers #
####################
[tap-firecracker_1.info]
ipv4 = "10.0.0.2"

[tap-firecracker_1.services.vast]
endpoint = "10.0.0.2:42000"

[tap-firecracker_1.services.vast-client]
endpoint = "10.0.0.1:42000"
broker = true
pcap.enable = false
pcap.interface = "enp0s5"


#########################
# tap-cloud-hypervisors #
#########################
[tap-cloud-hypervisor_1.info]
ipv4 = "10.0.0.3"

[tap-cloud-hypervisor_1.services.vast]
endpoint = "10.0.0.3:42000"

[tap-cloud-hypervisor_1.services.vast-client]
endpoint = "10.0.0.1:42000"
broker = false
pcap.enable = true
pcap.interface = "enp0s5"
