[tap_qemu_host.info]
ip = "10.0.0.1"

[tap_qemu_host.services.vast]
endpoint = "10.0.0.1:42000"

##############
# qemu hosts #
##############
[tap_qemu_1.info]
ipv4 = "10.0.0.5"

[tap_qemu_1.services.vast]
endpoint = "10.0.0.1:42000"

[tap_qemu_1.services.vast-client]
endpoint = "10.0.0.1:42000"
broker = false
pcap.enable = true
pcap.interface = "eth0"

[tap_qemu_2.info]
ipv4 = "10.0.0.6"

[tap_qemu_2.services.vast]
endpoint = "10.0.0.1:42000"

[tap_qemu_2.services.vast-client]
endpoint = "10.0.0.1:42000"
broker = false
pcap.enable = true
pcap.interface = "eth0"




####################
# tap_firecrackers #
####################
[tap_firecracker_1.info]
ipv4 = "10.0.0.2"

[tap_firecracker_1.services.vast]
endpoint = "10.0.0.2:42000"

[tap_firecracker_1.services.vast-client]
endpoint = "10.0.0.1:42000"
broker = true
pcap.enable = false
pcap.interface = "eth0"


#########################
# tap_cloud-hypervisors #
#########################
[tap_cloud-hypervisor_1.info]
ipv4 = "10.0.0.3"

[tap_cloud-hypervisor_1.services.vast]
endpoint = "10.0.0.3:42000"

[tap_cloud-hypervisor_1.services.vast-client]
endpoint = "10.0.0.1:42000"
broker = false
pcap.enable = true
pcap.interface = "eth0"
